# Build stage
FROM node:22 AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . ./
RUN npm run build

# Production stage
FROM nginx:alpine

# เปลี่ยน dist → build
COPY --from=builder /app/dist /usr/share/nginx/html

# เพิ่ม default.conf ใหม่ (หากมี)
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
